import React, { useState } from "react";
import Tags_bar from "../components/tags_btn";
import Check from "../assets/icons/check.svg";
// import Mini_calendar from '../../components/mini_calendar'
// import Cal_Modal from "../../components/Modal_Cal";
import { DateRange } from "react-date-range";
import { useRouter } from "next/router";
import { format } from "date-fns";
import Layout from "../components/layout";
import Head from "next/head";
import "react-date-range/dist/styles.css"; // main style file
import "react-date-range/dist/theme/default.css"; // theme css file
import { addDays } from "date-fns";

export default function AddGoal() {
    // const [showModal, setShowModal] = useState(false);
    const [startDate, setStartDate] = useState(new Date());
    const [endDate, setEndDate] = useState(new Date());
    const router = useRouter();

    const addGoal = (e) => {
        router.push({
            pathname: "/ongoing", // 왠지 데이터를 보낼 다른 방법이 있을 것 같다 찾아보자!!
            query: {
                startDate: startDate.toISOString(),
                endDate: endDate.toISOString(),
            },
        });
    };

    const handleSelect = (ranges) => {
        setStartDate(ranges.selection.startDate);
        setEndDate(ranges.selection.endDate);
    };

    const selectionRange = {
        startDate: startDate,
        endDate: endDate,
        key: "selection",
    };
    const formattedStartDate = format(new Date(startDate), "yy-MM-dd");
    const formattedEndDate = format(new Date(endDate), "yy-MM-dd");

    return (
        <Layout>
            <Head>
                <title>Goal For You Web!!</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className="mt-8 text-center text-fuchsia-600">add Goal!</h1>
            <div className="flex justify-center">
                <div className="">
                    <div className="mt-10">
                        <div className="container flex flex-col flex-wrap items-center pl-3 mx-auto md:flex-row">
                            <Check className="w-20 h-20 pr-2" />
                            <h2 className="text-fuchsia-600">
                                Input Goal's title
                            </h2>
                        </div>
                        <div className="pl-20 pb-11">
                            <input
                                className="input_style input_outline"
                                type="text"
                            />
                        </div>
                    </div>

                    <div className="container flex flex-col flex-wrap items-center pb-5 pl-3 mx-auto mt-10 md:flex-row">
                        <Check className="w-20 h-20 pr-2" />
                        <h2 className="text-fuchsia-600">Goal's period</h2>

                        {/* <div className="mt-3">
                            <button onClick={() => setShowModal(true)}
                                className="addGoal_target_date_btn"
                                >
                                <h3>Please select a target date</h3>
                            </button>
                        </div> */}
                    </div>

                    <div className="flex flex-row">
                        <div className="flex flex-row justify-between mt-16">
                            <div>
                                <div className="ml-32">
                                    <h4>start date</h4>
                                </div>
                                <div className="pb-3 ml-20 date_frame">
                                    <h4>{formattedStartDate}</h4>
                                </div>
                            </div>
                            <div>
                                <div className="ml-20">
                                    <h4>end date</h4>
                                </div>
                                <div className="pb-3 ml-7 date_frame">
                                    <h4>{formattedEndDate}</h4>
                                </div>
                            </div>
                        </div>

                        <div className="flex justify-center col-span-3 ml-24 border-2 w-96 shawdow-inner border-fuchsia-300 rounded-xl">
                            <DateRange
                                ranges={[selectionRange]}
                                minDate={addDays(new Date(), -300)}
                                dateDisplayFormat="yy-MM-dd"
                                rangeColors={["#E560C8"]}
                                onChange={handleSelect}
                            />
                        </div>
                    </div>

                    <div className="container flex flex-col flex-wrap items-center pb-5 pl-3 mx-auto mt-7 md:flex-row">
                        <div className="container flex flex-col flex-wrap items-center mx-auto lg:inline-flex md:flex-row">
                            <Check className="w-20 h-20 pr-2" />
                            <h2 className="text-fuchsia-600">Choice Tags</h2>
                        </div>

                        {/* <span className="relative inline-grid grid-cols-7 gap-1 ml-20 lg:inline-flex"> */}
                        <span className="flex ml-28">
                            <div className="flex space-x-2">
                                <Tags_bar tag_name="study" />
                                <Tags_bar tag_name="exercise" />
                                <Tags_bar tag_name="exam" />
                                <Tags_bar tag_name="work" />
                                <Tags_bar tag_name="project" />
                                <Tags_bar tag_name="planning" />
                                <Tags_bar tag_name="travel" />
                            </div>
                        </span>
                    </div>

                    <div className="flex justify-center mt-20">
                        <button onClick={addGoal} className="big_complete_btn">
                            <h3>Complete</h3>
                        </button>
                    </div>
                </div>
            </div>
        </Layout>
    );
}
