import Head from 'next/head'
import { Inter } from 'next/font/google'
import Layout from '../../components/layout'

const inter = Inter({ subsets: ['latin'] })

export default function Calendar() {
    return (
        <Layout>
          <Head>
            <title>Goal For You Web!!</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          
          <h1 className="text-3xl font-bold underline">
            캘린더입니다!
          </h1>
        </Layout>
      )
}
