import { useEffect, useState } from "react";
import Layout from "../components/layout";
import Head from "next/head";
import Card from "../components/Card.js";
import Link from "next/link";
import moment from "moment";
import { useRouter } from "next/router";
import Tag from "@/components/Tag";
export default function Community(){
  const boardList =[{
    id : 0,
    title : "Black Jacket",
    content : "Born in Paris",
  },
  {
    id : 1,
    title : "Black Jacket",
    content : "Born",
  }]
  const router = useRouter();  
  const { id } = router.query;
  const [BoardList, setBoardList] = useState([]);

  useEffect(()=>{
    const getBoardList = async() =>{
        const { data } = await axios.post(`/`);
        return data;
    }
    getBoardList().then(result =>setBoardList(result));
  },[]);

  return (
    <Layout>
      <Head>
           <title>Goal For You Web!!</title>
            <meta
               name="description"
               content="Generated by create next app"
            />
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <button onClick={() => router.push('/write')}>글쓰기</button>
        <div className="commu_mypage_frame">
            <h3 className="flex items-center justify-center font-bold font-local md:ml-auto">Our goals</h3>
            <div className="flex flex-row m-2">
                <Tag/>
            </div>
             <div className="flex items-center justify-center">
                {BoardList && BoardList.map((item, index) => (
                    (<Card key={item.index}
                           date = {moment(item.created).add(9,"hour").format('YYYY-MM-DD')} 
                           params={item.id}
                           title={item.title}
                           content={item.content}/>)
                    ))}
              </div>  
        </div>

      </Layout>
    );
}