import { useEffect, useState } from "react";
import Layout from "../components/layout";
import Head from "next/head";
import { data } from "./data.js";
import Card from "../components/Card.js";

export default function Community(){
  const boardList =[{
    id : 0,
    title : "Black Jacket",
    content : "Born in Paris",
  },
  {
    id : 1,
    title : "Black Jacket",
    content : "Born",
  }]

  return (
    <Layout>
      <Head>
           <title>Goal For You Web!!</title>
            <meta
               name="description"
               content="Generated by create next app"
            />
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="commu_mypage_frame">
            <h3 className="flex items-center justify-center font-bold font-local md:ml-auto">Our goals</h3>
            <button className="flex border-2 border-[#E560C8] justify-center w-32 h-8 text-[#e560c8] font-bold rounded-full">study</button>
            <button className="flex border-2 border-[#E560C8] justify-center w-32 h-8 text-[#e560c8] font-bold rounded-full">exercise</button>
             <div className="flex items-center justify-center">
                {boardList && boardList.map((item, index) => (
                    (<Card key={item.index} 
                           title={item.title}
                           content={item.content}/>)
                    ))}
              </div>
        </div>
      </Layout>
    );
}