import Head from 'next/head'
// import { Inter } from 'next/font/google'
import Layout from '../components/layout'

// const inter = Inter({ subsets: ['latin'] })

export default function MyPage() {
  return (
      <Layout>
        <Head>
          <title>Goal For You Web!!</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <div className="mt-3 ml-10 mr-10 frame">
          <div>
            마이페이지 입니다!
          </div>
        </div>
      </Layout>
    )
}
