import Head from "next/head";
import Layout from "../components/layout";
import OnGoing_nav_menu_bar from "../components/onGoing_nav_menu_bar";
import { useRouter } from "next/router";

export default function OnGoing() {
    // const [noShowDate, setNoShowDate] = useState(new Date());
    const router = useRouter();

    const { startDate, endDate } = router.query;
    console.log(router.query);

    // const formattedStartDate = format(new Date(startDate), "dd MMMM yy");
    // const formattedEndDate = format(new Date(endDate), "dd MMMM yy");
    // const range = `${formattedStartDate} - ${formattedEndDate}`;
    return (
        <Layout>
            <Head>
                <title>Goal For You Web!!</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="mt-3 mb-1">
                <OnGoing_nav_menu_bar />
            </div>

            <div className="ml-10 mr-10 frame">
                <div>Ongoing Goals</div>
            </div>
        </Layout>
    );
}
