import { useRouter } from "next/router";
import BoardText from "../components/BoardText";
import { useCallback, useState } from "react";
import ImageUploader from "../components/ImageUploader";
import Head from "next/head";
// import { Inter } from 'next/font/google'
import Layout from "../components/layout";

const write = () => {
    const router = useRouter();
    const [title, setTitle] = useState("");
    const [content, setContent] = useState("");
    const [image, setImage] = useState({
        image:"",
        preview_url:"/assets/logo.png",
    });
    
    const canSubmit = useCallback(() => {
        return content !== "" && title !== "";
      }, [title, content]);
    
      const handleSubmit = useCallback(async () => {
        try{
          const formData = new FormData();
          formData.append("title", title);
          formData.append("content", content);
          await api.post("/post", formData);
          window.alert("등록이 완료"); 
          router.push('/community');        
        } catch (e) {
            console.error(e);
        }
      }, [canSubmit]);

    return(
        <Layout>
            <Head>
                    <title>Goal For You Web!!</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                    <link rel="icon" href="/favicon.ico" />
            </Head> 
           
            <div className="frame">
                <div className="addboard">          
                    <div className="flex flex-col">
                        <ImageUploader/>
                        <BoardText
                            setTitle={setTitle} 
                            setContent={setContent} 
                            title={title} 
                            content={content}/>
                        
                    </div>
                <div className="submitButton">
                        <button
                            onClick={handleSubmit}
                            className="border-2 border-[#eeeee] w-20 h-18 font-local"
                            variant="outlined">등록하기</button>
                </div>
            </div>
            </div>

        </Layout>
    );
}

export default write;